version: "3.8"

services: 
  locationstation:
    build: .
    volumes: 
      - ./locationstation:/app/locationstation
    env_file:
      - .env
    ports:
      - 8000:8000
    container_name: locationstation-container
    depends_on: 
      - pgdb
  ngnix:
    build: ./ngnix
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - locationstation
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data/
volumes:
  pgdata:
  static: